# Linear Regression Practice

Adapted from http://www.ritchieng.com/machine-learning-linear-regression/

## 1. Reading Data using Panda

In [1]:
# conventional way to import pandas
import pandas as pd
import numpy as np

In [2]:
# read CSV file directly from a URL and save the results
# use .read_csv method and simply pass in the name of the files (local and through a url)
# to find out more about this method, click on the url and press shift + tab (twice)
# we set the index_col=0
#data = pd.read_csv('data/train.csv', keep_default_na=False, index_col=0)
data = pd.read_csv('data/train.csv', index_col=0)
Y2=data['SalePrice']
data=data.drop(columns=['SalePrice'])
print(data.shape)

tdata = pd.read_csv('data/test.csv', index_col=0)
print('test: ',tdata.shape)
#tdata.head()
frames = [data, tdata]
adata = pd.concat(frames)
#print(adata.shape)
# display the first 5 rows
#adata.head()
adata.head()

(1460, 79)
test:  (1459, 79)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

## 2. Completando información en la data

In [3]:
# Se analiza cada variable y se remplazan los datos nulos
# por la moda para strings y por la media para otros tipos de datos.
for var in adata:
        if adata[var].dtype!='O':
            adata[var].fillna((adata[var].mean()), inplace=True)
        else:
            adata[var].fillna((adata[var].mode()[0]), inplace=True)
adata_m=adata
adata_m.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,0,Ex,MnPrv,Shed,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,FR2,...,0,0,Ex,MnPrv,Shed,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,Inside,...,0,0,Ex,MnPrv,Shed,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,Corner,...,0,0,Ex,MnPrv,Shed,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,FR2,...,0,0,Ex,MnPrv,Shed,0,12,2008,WD,Normal

Analisis Histograma

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join('./outputs', fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)
# Resultado guardado en ./outputs  
%matplotlib inline
import matplotlib.pyplot as plt
import os
data.hist(bins=60, figsize=(20,15))
save_fig("attribute_histogram_plots")
plt.show()

## 3. Categorización

### 3.1 Con sklearn

data_m=data_m.iloc[:,:].values;
print(data.shape)
id=0
from sklearn.preprocessing import LabelEncoder

for var in data:
    if data[var].dtype=='O':
        #print(id)
        labelencoder_X=LabelEncoder()
        data_m[:,id]=labelencoder_X.fit_transform(data_m[:,id])
    id+=1

### 3.2 Con pandas

In [4]:
categorical_var=[]
for var in adata_m:
    if adata_m[var].dtype=='O':
        categorical_var.append(var)
adata_m = pd.get_dummies( adata_m, columns = categorical_var )

In [5]:
#categorical_var
adata_m.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
5,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [6]:
adata_m.shape

(2919, 288)

### 3.3 Normalizacion

In [7]:
for var in adata_m:
    adata_m[var]=(adata_m[var]-adata_m[var].min())/(adata_m[var].max()-adata_m[var].min())
adata_m.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,0.235294,0.150685,0.033420,0.666667,0.500,0.949275,0.883333,0.12250,0.125089,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.000000,0.202055,0.038795,0.555556,0.875,0.753623,0.433333,0.00000,0.173281,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.235294,0.160959,0.046507,0.666667,0.500,0.934783,0.866667,0.10125,0.086109,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.294118,0.133562,0.038561,0.666667,0.500,0.311594,0.333333,0.00000,0.038271,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
5,0.235294,0.215753,0.060576,0.777778,0.500,0.927536,0.833333,0.21875,0.116052,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [8]:
data2 = adata_m.iloc[:data.shape[0],:]
tdata2 = adata_m.iloc[data.shape[0]:,:]

## 4. Spliting data

### 4.1 Input-output

In [9]:
Y=(Y2-Y2.min())/(Y2.max()-Y2.min())
print(Y2.max()-Y2.min())
print(Y2.min())
Y=Y.iloc[:].values;
Y=np.reshape(Y, (Y.shape[0], 1))
X=data2.iloc[:,:].values;

720100
34900

### 4.2 Training-Testing

In [10]:
ordering= np.arange(X.shape[0])
np.random.shuffle(ordering)

In [11]:
train=ordering[0:int(X.shape[0]*0.8)]
test=ordering[int(X.shape[0]*0.8):X.shape[0]]
#print("train",train.shape)
#print("test",test.shape)
X_train=X[train,:]
X_test=X[test,:]
Y_train=Y[train]
Y_test=Y[test]

In [12]:
Y_train

array([[0.15289543],
       [0.2334398 ],
       [0.20149979],
       ...,
       [0.22371893],
       [0.32370504],
       [0.15983891]])

## 5. Training

In [ ]:
############################################
# PENDIENTE
# normal equation : (X'X)^-1.X'Y
############################################

In [ ]:
############################################
# BATCH
############################################
alfa=0.00001
reg=0.00001
epochs=100000
W=np.random.rand(1,X.shape[1])/X.shape[1]
id=0
for epoch in range(epochs):
    err_ep=0
    for indd in range(X_train.shape[0]):
        err=Y_train[indd]-np.matmul(X_train[indd],np.transpose(W))
        W+=alfa*(err*X_train[indd]+reg*W)
    if epoch%100==0:
        y_pred=np.matmul(X_test,np.transpose(W))*(Y2.max()-Y2.min())+Y2.min()
        y_test=Y_test*(Y2.max()-Y2.min())+Y2.min()
        err_ep=np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2));
        print('Epoca: ',epoch)
        print('err_t: ',err_ep)
print(W)
        
            
            
 
    #err=np.transpose(Y_train)-np.matmul(W,np.transpose(X_train))
 #   dw=alfa*np.matmul(err,X_train)/X.shape[0]
  #  W+=dw
   # #print('Y_train:', err)
    #
    #err_ep=0
    #print('err_ep: ',err_ep) 
   # if epoch%1000==0:
    #    y_pred=np.matmul(X_test,np.transpose(W))*(Y2.max()-Y2.min())+Y2.min()
     #   y_test=Y_test*(Y2.max()-Y2.min())+Y2.min()
      #  err_ep=np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2));
       # print('Epoca: ',epoch)
        #print('err_t: ',err_ep)
#print(W)

In [43]:
X_train[0].shape

(288,)

In [31]:
W[0].shape

(288,)

In [ ]:
############################################
# BATCH
############################################
alfa=0.0001
epochs=600000
W=np.random.rand(1,X.shape[1])/X.shape[1]
for epoch in range(epochs):
    err=np.transpose(Y_train)-np.matmul(W,np.transpose(X_train))
    dw=alfa*np.matmul(err,X_train)/X.shape[0]
    W+=dw
    #print('Y_train:', err)
    
    err_ep=0
    #print('err_ep: ',err_ep) 
    if epoch%1000==0:
        y_pred=np.matmul(X_test,np.transpose(W))*(Y2.max()-Y2.min())+Y2.min()
        y_test=Y_test*(Y2.max()-Y2.min())+Y2.min()
        err_ep=np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2));
        print('Epoca: ',epoch)
        print('err_t: ',err_ep)
print(W)

In [45]:
y_pred=np.matmul(X_test,np.transpose(W))*(Y2.max()-Y2.min())+Y2.min()
y_test=Y_test*(Y2.max()-Y2.min())+Y2.min()

In [46]:
##### RMSLE-KAGGLE
np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2))

0.16402993259474158

## 6. TESTEO

In [ ]:
tdata2.shape

In [ ]:
X_send=tdata2.iloc[:,:].values;
X_send.shape

In [ ]:
Y_send=np.matmul(X_send,np.transpose(W))*(Y2.max()-Y2.min())+Y2.min()
Y_send.shape

In [ ]:
df = pd.DataFrame(Y_send,columns = ["SalePrice"])
df.index = np.arange(1461, 1461+len(df))
df.to_csv("outputs/predictions2.csv")

In [ ]:
categorical_var=[]
id=0
for var in tdata:
    if tdata[var].dtype=='O':
        id+=1
        categorical_var.append(var)
print(id)
tdata = pd.get_dummies( tdata, columns = categorical_var )  
tdata.head()