# Linear Regression Practice

Adapted from http://www.ritchieng.com/machine-learning-linear-regression/

## 1. Reading Data using Panda

In [1]:
# conventional way to import pandas
import pandas as pd
import numpy as np

In [2]:
# Reading train and test csv files, merging after that
data = pd.read_csv('data/train.csv', index_col=0)
Y2=data['SalePrice']
data=data.drop(columns=['SalePrice'])
tdata = pd.read_csv('data/test.csv', index_col=0)
frames = [data, tdata]
adata = pd.concat(frames)
adata.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

## 2. Filling lost data

In [3]:
# Searching at each parameter for Nan data 
for var in adata:
        if adata[var].dtype!='O':
            # For int and floats we use the mean
            adata[var].fillna((adata[var].mean()), inplace=True)
        else:
            # For string data we use the mode
            adata[var].fillna((adata[var].mode()[0]), inplace=True)
adata_m=adata
adata_m.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,0,Ex,MnPrv,Shed,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,FR2,...,0,0,Ex,MnPrv,Shed,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,Inside,...,0,0,Ex,MnPrv,Shed,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,Corner,...,0,0,Ex,MnPrv,Shed,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,FR2,...,0,0,Ex,MnPrv,Shed,0,12,2008,WD,Normal

## 3. Encoding categorical variables and normalization

### 3.1 Encoding categorical variables

In [4]:
# Creating a list with all the categorical variables in the dataset
categorical_var=[]
for var in adata_m:
    if adata_m[var].dtype=='O':
        categorical_var.append(var)
# Using the function get_dummies we use the list "categorical_var" and encode the categorical variables.
adata_m = pd.get_dummies( adata_m, columns = categorical_var )   
adata_m.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
5,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

### 3.2 Normalization

In [5]:
for var in adata_m:
    adata_m[var]=(adata_m[var]-adata_m[var].min())/(adata_m[var].max()-adata_m[var].min())
adata_m.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,0.235294,0.150685,0.033420,0.666667,0.500,0.949275,0.883333,0.12250,0.125089,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.000000,0.202055,0.038795,0.555556,0.875,0.753623,0.433333,0.00000,0.173281,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.235294,0.160959,0.046507,0.666667,0.500,0.934783,0.866667,0.10125,0.086109,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.294118,0.133562,0.038561,0.666667,0.500,0.311594,0.333333,0.00000,0.038271,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
5,0.235294,0.215753,0.060576,0.777778,0.500,0.927536,0.833333,0.21875,0.116052,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

## 4. Spliting data

### 4.1 Training-Test data

In [6]:
data2 = adata_m.iloc[:data.shape[0],:]
tdata2 = adata_m.iloc[data.shape[0]:,:]

### 4.2 Input-output

Spliting input-output only for training data

In [7]:
Y=(Y2-Y2.min())/(Y2.max()-Y2.min())
Y=Y.iloc[:].values;
Y=np.reshape(Y, (Y.shape[0], 1))
X=data2.iloc[:,:].values;

### 4.2 Training-Testing

In [8]:
# Create training and test dataset
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state = 0)

/home/alvaro/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

## 5. Training

In [9]:
# Fit Random Forest on Training Set
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=300, random_state=0)
regressor.fit(X_train, y_train)

# Score model
regressor.score(X_train, y_train)

/home/alvaro/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

0.980966126116459

## 6. Results

In [10]:
import matplotlib.pyplot as plt
%matplotlib inline

# Predict new result
y_pred = regressor.predict(X_test)
np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2))

0.11371021749983416

## 7. Test

In [11]:
tdata2.shape

(1459, 288)

In [12]:
X_send=tdata2.iloc[:,:].values;
X_send.shape

(1459, 288)

In [13]:
Y_send=regressor.predict(X_send)
Y_send=Y_send*(Y2.max()-Y2.min())+Y2.min()
Y_send

array([128564.67134921, 156224.42603175, 181587.22640212, ...,
       155549.93015873, 112336.70777778, 231251.57177778])

In [14]:
df = pd.DataFrame(Y_send,columns = ["SalePrice"])
df.index = np.arange(1461, 1461+len(df))
df.to_csv("outputs/predictions2.csv")

In [ ]:
Este metodo genero un error de 0.14